### ISSUE TITLE
Duplicate customer ID

### ISSUE THREAD

**Issue by emtiazzahid** [lmsqueezy/laravel#103]
```private function resolveBillable(array $payload)
    {
        $custom = $payload['meta']['custom_data'] ?? null;

        if (! isset($custom) || ! is_array($custom) || ! isset($custom['billable_id'], $custom['billable_type'])) {
            throw new InvalidCustomPayload;
        }

        return $this->findOrCreateCustomer(
            $custom['billable_id'],
            (string) $custom['billable_type'],
            (string) $payload['data']['attributes']['customer_id']
        );
    }
 ```
I am using the User model as billable, when I try to pay from the same lemon squeezy account but a different laravel user it does not let me create a customer as lemon_squeezy_id is unique in the lemon_squeezy_customers table.
Maybe I am missing something, can you please give me a clue?

**Comment by driesvints** [comment]
What do you mean with "from the same lemon squeezy account"? Can you share some code?

**Comment by emtiazzahid** [comment]
when i test my application i use different users, but as I logged in to lemonsqueezy it gives same customer ID. in that case when I try to purchase subscription it gives ```integrity constraint violation: 1062 duplicate entry for key 'lemon_squeezy_customers``` that error.

**Comment by driesvints** [comment]
I really need code examples to reproduce this otherwise it's a shot in the dark at what you're trying todo.

**Comment by driesvints** [comment]
You absolutely need webhooks for this to work. The package can't function without it. You can take the approach of production is the command isn't working for you: https://github.com/lmsqueezy/laravel?tab=readme-ov-file#webhooks-in-production. 

> thats why i added the route in my web.php

you don't need to do that. The package registers this for you.

> and copied the controller WebhookController to my App/Http/Controllers folder with changing namespace

You don't need to do that either. What did you change in this controller?

> Here is my web.php full code

You're building the checkout link manually without using the package's documented way of starting a checkout. This isn't supported and cannot work because of how the package works internally. Please only use the documented way to use this package and create checkouts.

I feel like you're doing too much manually and overriding things which is beyond what I can help with sorry.

**Comment by emtiazzahid** [comment]
Thanks for your reply and valuable time.
the webhook was working fine with that custom route, It was just a copy of the controller without any modification.

Without webhook delivery, I think that database error wouldn't be produced.
anyway, I removed that route and controller also.

and now I using the route from the documentation 
```
Route::get('/buy', function (Request $request) {
    return $request->user()->checkout('variant-id');
});
``` 
so here is my web.php file in live
```<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

Route::view('/', 'welcome');

Route::middleware(['auth', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

Route::get('/buy', function (Request $request) {
    return $request->user()->checkout('417893');
});

require __DIR__.'/auth.php';
```
here only variation ID is added, if I visit the site it redirects to the checkout of my product and stores the data successfully with webhook. 
but the problem remains the same for the second laravel user with the same lmsqueezy customer.

```
Local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2735709' for key
```

Thanks
